events {}
http {
  upstream game { server game-server:9000; }
  server {
    listen 80;
    # REST da API
    location /api/ {
      proxy_pass http://game/;
    }
    # WebSocket (realtime: posição dos jogadores, chat, matchmaking)
    location /ws {
      proxy_pass http://game/ws;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_read_timeout 600s;
    }
  }
}
