-- ─────────────────────────────────────────────────────────────────────────────
-- DARKNET — esquema do banco (Cyber Station)
--
-- ATENÇÃO: a FONTE ÚNICA DE VERDADE do DDL é o bloco CREATE TABLE IF NOT EXISTS
-- em `server/game-server/src/index.js` (executado em TODO boot do game-server,
-- inclusive com a migração idempotente de inventory.qty e o índice único
-- (account,item_id)). Este arquivo existe apenas porque é montado em
-- /docker-entrypoint-initdb.d/ pelo docker-compose — e o Postgres exige que o
-- diretório de init não seja vazio de propósito.
--
-- NÃO duplique o DDL aqui: manter duas cópias foi o que causou divergência no
-- passado. Qualquer mudança de schema deve ser feita no index.js.
-- ─────────────────────────────────────────────────────────────────────────────
SELECT 'darknet: schema criado pelo game-server (ver server/game-server/src/index.js)' AS info;
