-- ─────────────────────────────────────────────────────────────────────────────
-- DARKNET — database schema (Cyber Station)
--
-- ATTENTION: the SINGLE SOURCE OF TRUTH for the DDL is the CREATE TABLE IF NOT EXISTS
-- block in `server/game-server/src/index.js` (executed on EVERY game-server boot,
-- including the idempotent migration of inventory.qty and the unique index
-- (account,item_id)). This file exists only because it is mounted in
-- /docker-entrypoint-initdb.d/ by docker-compose — and Postgres requires the
-- init directory not to be empty on purpose.
--
-- DO NOT duplicate the DDL here: maintaining two copies was what caused divergence in
-- the past. Any schema change must be made in index.js.
-- ─────────────────────────────────────────────────────────────────────────────
SELECT 'darknet: schema created by game-server (see server/game-server/src/index.js)' AS info;
